export const topOffers = [
  {
    id: 1,
    amount: 100,
    day: 1,
    data: '100MB',
    cashBack: 3,
    currency: '₦',
  },
  {
    id: 2,
    amount: 200,
    day: 3,
    data: '200MB',
    cashBack: 6,
    currency: '₦',
  },
  {
    id: 3,
    amount: 300,
    day: 1,
    data: '1GB',
    cashBack: 9,
    currency: '₦',
  },
  {
    id: 4,
    amount: 500,
    day: 2,
    data: '2.5GB',
    cashBack: 15,
    currency: '₦',
  },
  {
    id: 5,
    amount: 500,
    day: 7,
    data: '1GB',
    cashBack: 15,
    currency: '₦',
  },
  {
    id: 6,
    amount: 1000,
    day: 30,
    data: '1.5GB',
    cashBack: 30,
    currency: '₦',
  },
  {
    id: 7,
    amount: 1000,
    day: 7,
    data: '7GB',
    cashBack: 54,
    currency: '₦',
  },
  {
    id: 8,
    amount: 1500,
    day: 7,
    data: '6GB',
    cashBack: 45,
    currency: '₦',
  },
  {
    id: 9,
    amount: 1500,
    day: 30,
    data: '3GB',
    cashBack: 45,
    currency: '₦',
  },
  {
    id: 10,
    amount: 2000,
    day: 30,
    data: '4.5GB',
    cashBack: 60,
    currency: '₦',
  },
  {
    id: 11,
    amount: 3000,
    day: 30,
    data: '10GB',
    cashBack: 90,
    currency: '₦',
  },
  {
    id: 12,
    amount: 3500,
    day: 30,
    data: '4.5GB',
    cashBack: 105,
    currency: '₦',
    youtubeNight: '40GB',
  },
];

export const daily = [
  {
    id: 1,
    amount: 100,
    day: 1,
    data: '100MB',
    cashBack: 3,
    currency: '₦',
  },
  {
    id: 2,
    amount: 200,
    day: 3,
    data: '200MB',
    cashBack: 6,
    currency: '₦',
  },
  {
    id: 3,
    amount: 300,
    day: 1,
    data: '1GB',
    cashBack: 9,
    currency: '₦',
  },
  {
    id: 4,
    amount: 500,
    day: 2,
    data: '2.5GB',
    cashBack: 15,
    currency: '₦',
  },
  {
    id: 5,
    amount: 700,
    day: 2,
    data: '3GB',
    cashBack: 21,
    currency: '₦',
  },
  {
    id: 6,
    amount: 300,
    day: 3,
    data: '400MB',
    cashBack: 6,
    currency: '₦',
  },
  {
    id: 7,
    amount: 1000,
    day: 3,
    data: '20MB',
    cashBack: 54,
    currency: '₦',
    talkTime: 1000,
  },
];

export const weekly = [
  {
    id: 7,
    amount: 300,
    day: 7,
    data: '7GB',
    cashBack: 54,
    currency: '₦',
  },
  {
    id: 8,
    amount: 1500,
    day: 7,
    data: '6GB',
    cashBack: 45,
    currency: '₦',
  },
  {
    id: 9,
    amount: 1500,
    day: 30,
    data: '3GB',
    cashBack: 45,
    currency: '₦',
  },
  {
    id: 10,
    amount: 2000,
    day: 30,
    data: '4.5GB',
    cashBack: 60,
    currency: '₦',
  },
  {
    id: 11,
    amount: 3000,
    day: 30,
    data: '10GB',
    cashBack: 90,
    currency: '₦',
  },
  {
    id: 12,
    amount: 3500,
    day: 30,
    data: '4.5GB',
    cashBack: 105,
    currency: '₦',
    youtubeNight: '40GB',
  },
];
export const monthly = [
  {
    id: 1,
    network: 'MTN',
    network_id: 1,
    amount: 135,
    planType: 'SME',
    day: 30,
    data: '500MB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 2,
    network: 'MTN',
    network_id: 1,
    amount: 270,
    planType: 'SME',
    day: 30,
    data: '1GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 3,
    network: 'MTN',
    network_id: 1,
    amount: 540,
    planType: 'SME',
    day: 30,
    data: '2GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 4,
    network: 'MTN',
    network_id: 1,
    amount: 810,
    planType: 'SME',
    day: 30,
    data: '3GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 5,
    network: 'MTN',
    network_id: 1,
    amount: 1350,
    planType: 'SME',
    day: 30,
    data: '5GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 6,
    network: 'Globacom',
    network_id: 3,
    amount: 2700,
    planType: 'SME',
    day: 30,
    data: '10GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 20,
    network: 'Globacom',
    network_id: 3,
    amount: 480,
    planType: 'GIFTING',
    day: 30,
    data: '1.35GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 21,
    network: 'Globacom',
    network_id: 3,
    amount: 970,
    planType: 'GIFTING',
    day: 30,
    data: '2.9GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 22,
    network: 'Globacom',
    network_id: 3,
    amount: 1450,
    planType: 'GIFTING',
    day: 30,
    data: '4.1GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 24,
    network: 'Globacom',
    network_id: 3,
    amount: 1900,
    planType: 'GIFTING',
    day: 30,
    data: '5.8GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 36,
    network: '9Mobile',
    network_id: 1,
    amount: 880,
    planType: 'GIFTING',
    day: 30,
    data: '1.5GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 37,
    network: '9Mobile',
    network_id: 1,
    amount: 1000,
    planType: 'GIFTING',
    day: 30,
    data: '2GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 38,
    network: '9Mobile',
    network_id: 1,
    amount: 1300,
    planType: 'GIFTING',
    day: 30,
    data: '3GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 39,
    network: '9Mobile',
    network_id: 1,
    amount: 1750,
    planType: 'GIFTING',
    day: 30,
    data: '4.5GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 46,
    network: 'Airtel Nigeria',
    network_id: 2,
    amount: 103,
    planType: 'COOPERATE GIFTING',
    day: 30,
    data: '500MB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 47,
    network: 'Airtel Nigeria',
    network_id: 2,
    amount: 205,
    planType: 'COOPERATE GIFTING',
    day: 30,
    data: '1GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 48,
    network: 'Airtel Nigeria',
    network_id: 2,
    amount: 410,
    planType: 'COOPERATE GIFTING',
    day: 30,
    data: '2GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 49,
    network: 'Airtel Nigeria',
    network_id: 2,
    amount: 1025,
    planType: 'COOPERATE GIFTING',
    day: 30,
    data: '5GB',
    cashBack: 0,
    currency: '₦',
  },
  {
    id: 56,
    network: 'Airtel Nigeria',
    network_id: 2,
    amount: 2050,
    planType: 'COOPERATE GIFTING',
    day: 30,
    data: '10GB',
    cashBack: 0,
    currency: '₦',
  },
];

// 46
// AIRTEL	COOPERATE GIFTING	500MB	₦103.00	1 Month
// 47
// AIRTEL	COOPERATE GIFTING	1GB	₦205.00	1 Month
// 48
// AIRTEL	COOPERATE GIFTING	2GB	₦410.00	1 Month
// 49
// AIRTEL	COOPERATE GIFTING	5GB	₦1,025.00	1 Month
// 50
// MTN	COOPERATE GIFTING	500MB	₦110.00	1 Month
// 51
// MTN	COOPERATE GIFTING	1GB	₦220.00	1 Month
// 52
// MTN	COOPERATE GIFTING	2GB	₦440.00	1 Month
// 53
// MTN	COOPERATE GIFTING	3GB	₦660.00	1 Month
// 54
// MTN	COOPERATE GIFTING	5GB	₦1,100.00	1 Month
// 55
// MTN	COOPERATE GIFTING	10GB	₦2,200.00	1 Month
// 56
// AIRTEL	COOPERATE GIFTING	10GB	₦2,050.00	1 Month
